## for only installing postgres & keycloak
dashboard-service:
  enabled: false

ngsi-service:
  enabled: false

orchideo-connect-service:
  enabled: false

mail-service:
  enabled: false

infopin-service:
  enabled: false

static-data-service:
  enabled: false

report-service:
  enabled: false

usi-platform-service:
  enabled: false

data-translation-service:
  enabled: true
  service:
    enabled: false  # Disable service creation since no endpoints are needed
  image:
    repository: smartcity/data-translation-service
    tag: 'latest-dev'
    pullPolicy: IfNotPresent

internal-data-service:
  enabled: true
  service:
    enabled: true
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/internal-data-service
    tag: 1.1.12
    pullPolicy: Always

frontend:
  enabled: false

migrations:
  enabled: true
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/migrations
    tag: 1.1.12
    pullPolicy: Always
